### ISSUE TITLE
Docker container does not start/expose Django server

### ISSUE THREAD

**Issue by ebastos** [ebastos/shell-history#7]
Currently a manual docker exec is necessary to start the Django web interface. Only the gprc service is exposed.

**Comment by jmartin84** [comment]
I can take this, though I'll need some more context. It sounds like the container is running two different processes?

**Comment by ebastos** [comment]
Thanks, @jmartin84 

That is correct. There are two services:
1. The gRPC backend listening on 50051, which is automatically started
2. The Django webserver which presents the history. 

The 2nd one has to be manually mapped and started.

```
$ docker container inspect shell-history
...
            "PortBindings": {
                "50051/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "50051"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8000"
                    }
                ]
            },
...
```


```
$ docker exec -ti shell-history /bin/sh
/app # ps auxw
PID   USER     TIME  COMMAND
    1 root      7:05 python server.py
    9 root      0:00 ash
   19 root      0:00 python manage.py runserver 0.0.0.0:80
   20 root     13h05 /usr/local/bin/python manage.py runserver 0.0.0.0:80
   72 root      0:00 /bin/sh
   79 root      0:00 ps auxw
/app # 
```

You can see that PID 20 was manually started sometime after the container booted.

Please, let me know if you need more details ;)

**Comment by jmartin84** [comment]
Thanks for the details, that should be plenty. One more question though.

Whats the intended use case of this image? Is it meant to be hosted on some server or just run locally by the end user?

I ask because generally you want to avoid starting multiple processes in a docker container since docker isn't really able to exit cleanly on failure unless the one process its watching is the one that fails.

That being said, if its just meant to be run locally then its really not a big deal.

So I can either make both processes run or split it up into a multi-image solution (maybe as another ticket after completing this as a stop gap?). Either way I'll leave it up to you.

**Comment by ebastos** [comment]
As it is this image was only meant to be a quick-start for testing/evaluation.
But going forward that could use a more well-thought structure as you are suggesting. 

> So I can either make both processes run or split it up into a multi-image solution (maybe as another ticket after completing this as a stop gap?). Either way I'll leave it up to you.

That sounds like a good idea.

Thanks again.
